### ISSUE TITLE
Question: are aggregations possible - and more generally some example snippets

### ISSUE THREAD

**Issue by javadba** [dwt/fluent#3] opened 2018-10-21 01:21 UTC
Some snippets of code showing how to use this library- beyond the  enticing one in the README.md would be sooo helpful.

**Comment by javadba** [comment] 2018-10-21 01:57
Here is a scala snippet that would be great to see a translation to fluentpy

```
val a = ((1 to 50)
  .map(_ * 4)
  .filter( _ <= 170)
  .filter(_.toString.length == 2)
  .filter (_ % 20 == 0)
  .zipWithIndex      // Aggregation
  .map{ case(x,n) =>     
    val msg = s"Result[$n]=$x"   // Side effects
    prinln(msg)
    msg 
  } .mkString("  .. "))   // Aggregation
```
And here was my (v v poor..) attempt to translate most of it:

```
import fluentpy as _
a = (
  _(range(1,50+1))
  .map(_.each * 4)
  .filter(_.each <= 170)
  .filter(len(str(_.each))==2)
  .filter(_.each % 20 == 0)
  .call(enumerate)
  .tupleize()
  .map('Result[%d]=%s' %(_.each[0],_.each[1]))  # could not see how to do side effects
   ._
 )
print(','.join(a))  # could not see how to bake that in to the fluent call
```

**Comment by dwt** [comment] 2018-10-23 13:27
```python
import fluentpy as _
(
  _(range(1,50+1))
  .map(_.each * 4)
  .filter(_.each <= 170)
  .filter(lambda each: len(str(each))==2)
  .filter(lambda each: each % 20 == 0)
  .enumerate()
  .map(lambda each: 'Result[%d]=%s' %(each[0],each[1]))
  .join(',')
  .print()
)
```

Here you go. The biggest limitation (from what you where trying to achieve) is probably that I haven't found a way to build up complex operations as callables. Thus `.filter(len(str(_.each))==2)` doesn't work and instead has to be expressed with an old-style lambda. `.filter(lambda each: len(str(each))==2)` Ah well.

**Comment by dwt** [comment] 2018-10-23 13:29
As for the docs - I'd love some Ideas how to improve them, as this has been pretty much  giant experiment by me to this point to see how far I can push python into this direction. So Suggestions welcome.

Maybe just an FAQ style section with examples of how to translate stuff?

Also: Have you had a look at the code and has it actually helped you understand how this library works?

**Comment by javadba** [comment] 2018-10-23 13:36
Thx so much for that example code: I'm definitely onboard with this library.

> look at code
I tend to do that after being convinced of a library's usefulness.  I'm "there" now .  I did contribute to the pipe library - but the problem with it is too much needs to be built by hand. What you have here has a higher starting point in terms of what works out of the box.

I'll look at the code more carefully over Christmas break: got two night classes and no cycles for a bit.
thx again.

**Comment by javadba** [comment] 2018-11-10 19:14
Hi - I am starting to incorporate this into my work. 

The docs have the following example:

`curl -sL 'https://www.iblocklist.com/lists.php' | egrep -A1 'star_[345]' |  python3 -m fluentpy "lib.sys.stdin.read().findall(r'value=\'(.*)\'') .map(lib.xml.sax.saxutils.unescape).map(print)"
`
The result is:

```
fluentpy.wrap(http://list.iblocklist.com/?list=ydxerpxkpcfqjaybcssw&fileformat=p2p&archiveformat=gz)
fluentpy.wrap(http://list.iblocklist.com/?list=gyisgnzbhppbvsphucsw&fileformat=p2p&archiveformat=gz)
fluentpy.wrap(http://list.iblocklist.com/?list=uwnukjqktoggdknzrhgh&fileformat=p2p&archiveformat=gz)
fluentpy.wrap(http://list.iblocklist.com/?list=imlmncgrkbnacgcwfjvh&fileformat=p2p&archiveformat=gz)
fluentpy.wrap(http://list.iblocklist.com/?list=plkehquoahljmyxjixpu&fileformat=p2p&archiveformat=gz)
..

```

Now I tried _unwrapping_ by adding a `._`  : 

`curl -sL 'https://www.iblocklist.com/lists.php' | egrep -A1 'star_[345]' |  python3 -m fluentpy "lib.sys.stdin.read().findall(r'value=\'(.*)\'') .map(lib.xml.sax.saxutils.unescape).map(print)._"`

But this had no effect: still printing out `fluentpy.wrap(val)`

Given this is code copied and pasted from the docs - can you comment on how to do the unwrapping properly?

**Comment by javadba** [comment] 2018-11-10 21:06
btw Just browsed the main `fluent.py` : really nice work afaict (i'm only an avg python programmer so take that fwiw).  The `curry` method in particular is formidable: is that intended for any external/public uses - or is it an internal support mechanism?

**Comment by dwt** [comment] 2018-11-12 08:36
> Hi - I am starting to incorporate this into my work.

Cool!

> The docs have the following example:
> 
> `curl -sL 'https://www.iblocklist.com/lists.php' | egrep -A1 'star_[345]' | python3 -m fluentpy "lib.sys.stdin.read().findall(r'value=\'(.*)\'') .map(lib.xml.sax.saxutils.unescape).map(print)" `
> 
> Given this is code copied and pasted from the docs - can you comment on how to do the unwrapping properly?

Ah well, the problem is that importing a function via `lib.xml.sax.saxutils.unescape` returns it pre-wrapped. That is useful, because it means you can chain off of return values from these functions immediately, without needing to wrap them first, but it is counterproductive in this example. :/ Well, what you get for not having executable documentation...

The easiest fix for this is to explicitly unwrap the function imported via `lib....` before it is used. I.e. 

`curl -sL 'https://www.iblocklist.com/lists.php' | egrep -A1 'star_[345]' | python3 -m fluentpy "lib.sys.stdin.read().findall(r'value=\'(.*)\'') .map(lib.xml.sax.saxutils.unescape._).map(print)" `

Not quite as intuitive as I'd like. :-/

Thats actually an example I have removed from the docs already on the dev-version, as I don't really want to advertise the iblocklist service, but that hasn't been released yet. Well, something I should get around to soon.

**Comment by javadba** [comment] 2018-11-12 15:16
But it is a great example of the utility of your library - why not some other page that "would not mind" being advertised?

**Comment by dwt** [comment] 2018-11-13 16:13
> But it is a great example of the utility of your library - why not some other page that "would not mind" being advertised?

Sure, do you have an Idea? The spirit of the example I quite like, its just rather that site I don’t want to affiliate the project with.

**Comment by dwt** [comment] 2018-12-03 17:39
Feel free to open another issue for the example - I’m just closing this bug as it’s main issue is resolved.

**Closed by dwt** 2018-12-03 17:39 UTC
